changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
  categories:
    - title: Security
      labels:
        - security
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Added
      labels:
        - enhancement
        - feature
    - title: Fixed
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - maintenance
        - ci
    - title: Other changes
      labels:
        - "*"
